name: sf_test
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  graphql_flutter: ^5.0.0
#  charts_flutter: ^0.11.0
#  shrink_sidemenu: ^2.0.0+1
#  liquid_ui: ^1.0.0+9
#  spritewidget: ^0.9.24
#  callkeep: ^0.3.2
#  uuid: ^3.0.5
  get: ^4.3.8
  google_maps_flutter: ^2.1.1
  collection: ^1.15.0
  sign_in_with_apple: ^3.3.0
  local_auth: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/weathersprites.png
    - images/icon-rain.png
    - images/2.jpg
    - images/weathersprites.json